export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const TOGGLE_ONE_TASK = 'TOGGLE_ONE_TASK';
export const DELETE_ONE_TASK = 'DELETE_ONE_TASK';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
